### PR TITLE
fix(*): fix lapis dependency to avoid pgmoon duplication

### PR DESCRIPTION
**Pull request by windmgc**
Kong is currently using its own fork of pgmoon called `kong-pgmoon`
https://github.com/Kong/pgmoon/blob/d43ec5366d12dcab6a8e1207e8d4b2c7120c0b62/kong-pgmoon-2.3.2.0-1.rockspec#L1

Pinning the package `pgmoon` here will result in duplicate `pgmoon` installed in the Kong package

KAG-1695

### CODE REVIEW

**Comment by Tieske** [comment]
the rockspecs we actually use are not on this branch (`master`), there should be another one

**Comment by windmgc** [comment]
@Tieske Nice finding! I was just wondering how did those release come from 😃

**Comment by Tieske** [comment]
this one is the latest; https://github.com/Kong/lapis/tree/chore/kong-lapis-1.14.0.2

But that branch doesn't have a rockspec.

@bungle how does this work? should we just download the current rockspec from LuaRocks, update the dependency and the rockspec revision, and then upload again? without comitting it in this repo?

**Comment by bungle** [comment]
@windmgc can you instead open this against:
https://github.com/Kong/lapis/releases/tag/v1.14.0.2

**Comment by bungle** [comment]
Or create: `chore/kong-lapis-1.14.0.3` out from: https://github.com/Kong/lapis/tree/chore/kong-lapis-1.14.0.2

And get this pr on `chore/kong-lapis-1.14.0.3`

**Comment by windmgc** [comment]
I'm quite confused about the way the CI running, so it might be impossible to fix on this old branch(simply adding lua-cjson in the github workflow won't help, it has other problems).

Since there is no manual on the release process on this library, @bungle I suggest we merge this first since it only contains a dependency name fix, and after the merge, I'm going to:
- [x] tag the latest commit on the branch [chore/kong-lapis-1.14.0.3] with v1.14.0.3
- [x] release on github
- [x] `luarocks pack kong-lapis-1.14.0.3-1.rockspec` locally and `luarocks upload` to luarocks
- [ ] update ce/ee dependency accordingly

**Pull request merged**
